packets:
  capture_mode: "pcap" # interface or pcap
  direction:
    mode: "ip" # mac or ip
    client_macs:
      - ""
    client_ips:
      - "131.236.0.0/16"
      - "129.94.0.0/16"
      - "149.174.0.0/16"
      - "10.0.0.0/8"
      - "192.168.0.0/16"

processors:
  dump:
    enabled: true
    path: "./files/dumps/dump.json.log"
    topics:
      - "packet_parser.metadata"
      - "classification"
      - "flow.attach_telemetry"
      - "telemetry.tcp_retransmit_simple"
      - "telemetry.flowpulse"
      - "telemetry.tcp_rtt"

  header_classifier:
    classes:
      amazonprime:
        client_ip: '131.236.139.10/32'
        server_ip: '117.121.253.125/32'
        client_port: '*' # syntax: 'n': p == n, 'm-n': m<=p<=n
        server_port: '443'
        protocol: '6'
      zoomudp:
        client_ip: '10.42.0.159/32'
        #client_ip: '10.100.113.110/32'
        server_ip: '144.195.0.0/16'
        client_port: '*' # syntax: 'n': p == n, 'm-n': m<=p<=n
        server_port: '8801'
        protocol: '17'
      zoomtcp:
        client_ip: '10.42.0.159/32'
        #client_ip: '10.100.113.110/32'
        server_ip: '144.195.0.0/16'
        client_port: '*' # syntax: 'n': p == n, 'm-n': m<=p<=n
        server_port: '443'
        protocol: '6'
      

  telemetry_manager:
    enabled: true
    classes:
      https: ['tcp_rtt', 'flowpulse', 'tcp_retransmit']


telemetry:
  flowpulse:
    interval_ms: 1000
  tcp_retransmit:
    interval_ms: 1000

